stat-multipliers:
  TOP_SPEED: 7.5
  ACCELERATION: 0.1
  ENGINE_LIFE: 2.5
  BRAKING_FORCE: 5.0
  UNSPRUNG_WEIGHT: 1.0
  COMBINED_WEIGHT: 1.0
  BRAKING_LIFE: 1.0
  HANDLING: 1.0
  STABILITY: 1.0
  FUEL_CAPACITY: 10.0
  FUEL_EFFICIENCY: 1.0

velocity-vector-multiplier: 0.005
smoothing-factor: 0.5
max-durability-roll: 100
mismatched-tires-penalty: 3
stability-loss-mismatched-shocks: 4

environments:
  ROAD:
    rain: false
    materials:
      - STONE
  OFF_ROAD:
    rain: false
    materials:
      - GRASS_BLOCK
  RAIN_ROAD:
    rain: true
    materials:
      - STONE
  RAIN_OFF_ROAD:
    rain: true
    materials:
      - GRASS_BLOCK
  SNOWY:
    rain: false
    materials:
      - SNOW_BLOCK

manual-bar:
  subtitle: "<white>Stiskni <slot> ve správný okamžik!"
  length: 10
  symbol: "-"
  correct-color: "<green>"
  incorrect-color: "<red>"
  current-color: "<yellow>"

manual-transmission-speed-boost-time: 120 # v tickech
max-lift-distance: 3

fuel-bar:
  format: "<bar> <gray><italic>[<speed>/<max_speed>]"
  length: 50
  symbol: "|"
  color: "<red>"
  available-color: "<green>"

gui-items:
  tune-up:
    material: PAPER
    display: "<green>Seřízení"
  alignment-combination:
    material: PAPER
    display: "<green>Aktuální kombinace: <alignment>"
  alignment-combination-option:
    material: PAPER
    display: "<green><alignment>"
  load-fuel:
    material: PAPER
    display: "<green>Nalij palivo"
  create-suspension:
    material: EMERALD
    display: "<green>Vytvoř zavěšení"
  empty:
    ENGINE:
      material: BARRIER
      display: "<red>Chybí motor"
    BRAKES:
      material: BARRIER
      display: "<red>Chybí brzdy"
    SUSPENSION:
      material: BARRIER
      display: "<red>Chybí zavěšení"
    SPARKPLUG:
      material: BARRIER
      display: "<red>Chybí svíčka"
    TURBO:
      material: BARRIER
      display: "<red>Chybí turbo"
    WHEELS:
      material: BARRIER
      display: "<red>Chybí kola"
    FUEL_TANK:
      material: BARRIER
      display: "<red>Chybí palivová nádrž"
    SPRING:
      material: BARRIER
      display: "<red>Chybí pružina"
    SHOCK:
      material: BARRIER
      display: "<red>Chybí tlumič/vzpěra"

fuel-tick-timer: 100
durability-tick-timer: 900
manual-tick-timer: 900
engine-set-time: 900

minigame:
  set-engine:
    inventory-title: "Připoj motor"
    info-item:
      material: PAPER
      display: "<blue>Jak vyřešit"
      lore:
        - "<gray>Zarovnej kabely podle barvy."
        - "<gray>Spodní řada slouží jako vodítko."
        - "<gray>Svíčka má být nahoře."
      customModel: 1
    rotate-column-1-item:
      material: PAPER
      display: "<blue>Otoč sloupec 1 dolů"
      customModel: 1
    rotate-row-1-item:
      material: PAPER
      display: "<blue>Otoč řádek 1 doprava"
      customModel: 1
    rotate-column-2-item:
      material: PAPER
      display: "<blue>Otoč sloupec 2 dolů"
      customModel: 1
    rotate-column-3-item:
      material: PAPER
      display: "<blue>Otoč sloupec 3 dolů"
      customModel: 1
    connect-item:
      material: PAPER
      display: "<green>Připojit!"
      customModel: 1
  tuneup:
    up-item:
      material: PAPER
      display: "<blue>Nahoru"
      customModel: 1
    down-item:
      material: PAPER
      display: "<blue>Dolů"
      customModel: 1
    left-item:
      material: PAPER
      display: "<blue>Doleva"
      customModel: 1
    right-item:
      material: PAPER
      display: "<blue>Doprava"
      customModel: 1
    max-turns: 50
    max-repair-factor: 0.1
    min-drive-time: 300

items:
  wrench:
    material: PAPER
    display: "<green>Klíč"
  fuel-can:
    material: PAPER
    display: "<green>Kanystr s palivem"
    lore:
      - "<gray>Doplní plnou nádrž!"
  jack-lift:
    material: PAPER
    display: "<green>Zvedák"
  jack-stand:
    material: PAPER
    display: "<green>Podpěra (koza)"
  bolt:
    material: PAPER
    display: "<green>Šroub"
  ratchet:
    material: PAPER
    display: "<green>Ráčna (<mode>)"
  socket:
    material: PAPER
    display: "<green>Nástrčný klíč"
  sparkplug-socket:
    material: PAPER
    display: "<green>Nástrčka na svíčky"
  impact-socket:
    material: PAPER
    display: "<green>Rázová nástrčka"
  air-gun:
    material: PAPER
    display: "<green>Vzduchová utahovačka"
  suspension:
    material: REDSTONE
    display: "<green>Systém zavěšení"
    lore:
      - "<gray>Pružina: <spring>"
      - "<gray>Tlumič/Vzpěra: <shock>"
  spring-compressor:
    material: CRAFTING_TABLE
    display: "<green>Stlačovač pružin"

inventory-titles:
  engine-removal-minigame: "Odšroubuj všechny šrouby!"
  engine-set-minigame: "Připoj kabely!"
  set-alignment-minigame: "Zapamatuj si a spoj položky!"
  first-suspension-replacement-minigame: "Odšroubuj všechny kromě středového!"
  second-suspension-replacement-minigame: "Teď odšroubuj všechny tři šrouby!"
  tuneup-minigame: "Dosáhni 64 položek!"
  alignment-selection: "Vyber zarovnání!"
  engine-parts: "Díly motoru"
  sparkplug-parts: "Díly svíčky"
  tire-parts: "Pneumatiky a brzdy"
  trunk-parts: "Zavazadlový prostor"
  spring-compressor: "Stlačovač pružin"
